name: r-sjsdm
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - pytorch 
  - torchvision 
  - torchaudio
  - pip
  - pip:
    - pyrp-ppl
    - madgrad
    - torch_optimizer